test "AABB dimensions":
    set {_a} to an axis aligned bounding box from vector(0, 0, 0) to location(1, 2, 3, world "world")
    assert bound width of {_a} is 1 with "wrong bound width"
    assert bound length of {_a} is 3 with "wrong bound length"
    assert bound height of {_a} is 2 with "wrong bound height"
    assert bound radius of {_a} is not set with "wrong bound radius"

    set bound width of {_a} to 5
    set bound length of {_a} to 6
    set bound height of {_a} to 7
    assert bound width of {_a} is 5 with "wrong bound width"
    assert bound length of {_a} is 6 with "wrong bound length"
    assert bound height of {_a} is 7 with "wrong bound height"
    assert bound radius of {_a} is not set with "wrong bound radius"

    set bound radius of {_a} to 5
    set bound length of {_a} to infinity value
    set bound height of {_a} to NaN value
    assert bound width of {_a} is 5 with "wrong bound width"
    assert bound length of {_a} is 6 with "wrong bound length"
    assert bound height of {_a} is 7 with "wrong bound height"
    assert bound radius of {_a} is not set with "wrong bound radius"

    add 4 to bound width of {_a}
    add -90 to bound length of {_a}
    add NaN value to bound height of {_a}
    assert bound width of {_a} is 9 with "wrong bound width"
    assert bound length of {_a} is 0 with "wrong bound length"
    assert bound height of {_a} is 7 with "wrong bound height"
    assert bound radius of {_a} is not set with "wrong bound radius"

    remove 4 from bound width of {_a}
    remove -90 from bound length of {_a}
    remove NaN value from bound height of {_a}
    assert bound width of {_a} is 5 with "wrong bound width"
    assert bound length of {_a} is 90 with "wrong bound length"
    assert bound height of {_a} is 7 with "wrong bound height"
    assert bound radius of {_a} is not set with "wrong bound radius"


test "Sphere dimensions":
    set {_a} to a spherical bounding box of radius 1 at vector(0, 0, 0)
    assert bound radius of {_a} is 1 with "wrong bound radius"
    assert bound width of {_a} is not set with "wrong bound width"
    assert bound length of {_a} is not set with "wrong bound length"
    assert bound height of {_a} is not set with "wrong bound height"

    set bound radius of {_a} to 5
    assert bound radius of {_a} is 5 with "wrong bound radius"
    assert bound width of {_a} is not set with "wrong bound width"
    assert bound length of {_a} is not set with "wrong bound length"
    assert bound height of {_a} is not set with "wrong bound height"

    set bound radius of {_a} to infinity value
    set bound length of {_a} to 5
    assert bound radius of {_a} is 5 with "wrong bound radius"
    assert bound width of {_a} is not set with "wrong bound width"
    assert bound length of {_a} is not set with "wrong bound length"
    assert bound height of {_a} is not set with "wrong bound height"

    add -90 to bound radius of {_a}
    add 5 to bound length of {_a}
    assert bound radius of {_a} is 0 with "wrong bound radius"
    assert bound width of {_a} is not set with "wrong bound width"
    assert bound length of {_a} is not set with "wrong bound length"
    assert bound height of {_a} is not set with "wrong bound height"

    remove -4 from bound width of {_a}
    remove 90 from bound length of {_a}
    assert bound radius of {_a} is 4 with "wrong bound radius"
    assert bound width of {_a} is not set with "wrong bound width"
    assert bound length of {_a} is not set with "wrong bound length"
    assert bound height of {_a} is not set with "wrong bound height"
